version: "3"
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: complex
  redis:
    image: 'redis:latest'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /server/node_modules
      - ./server:/server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PGUSER: root
      PGHOST: postgres
      PGDATABASE: complex
      PGPASSWORD: root
      PGPORT: 5432   
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /worker/node_modules
      - ./worker:/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /client/node_modules
      - ./client:/client
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'